core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth', include('social_django.urls', namespace='social')),
    path('results/', views.search, name='search'),
    path('privacy-policy', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service', views.terms, name='terms'),
    path('canvas-syllabus-tutorial', views.syllabus_tutorial, name='syllabus_tutorial'),
    path('resources', views.resources, name='resources'),
    path('feedback', views.feedback, name='feedback')
]

courses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('courses/<str:category>', views.category, name='category'),
    path('courses/<str:category>/<int:number>', views.course, name='course'),
    path('courses/<str:category>/<int:number>/review', views.review, name='review'),
    path('courses/<int:id>/syllabus', views.syllabus, name='syllabus'),
]

schulichgo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('', include('core.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

import datetime

class Course(models.Model):
    code = models.CharField(max_length=15)
    category = models.CharField(max_length=4)
    number = models.IntegerField()
    title = models.CharField(max_length=200)
    description = models.TextField()
    instructors = ArrayField(models.CharField(max_length=200))
    updated_at = models.DateTimeField(auto_now=True)

class Syllabus(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    syllabus = models.FileField(upload_to='syllabus/')
    updated_at = models.DateTimeField(auto_now=True)
    uploader = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

class Category(models.Model):
    category = models.CharField(max_length=4)
    category_title = models.CharField(max_length=200)

class Review(models.Model):
    current_year = int(datetime.datetime.now().year) #to enable user to pick up to the current year
    year_choices = range(current_year, 2000-1, -1)
    year_choices = tuple(zip(year_choices, year_choices)) #turning into a tuple because django expects actual value and human readable form, which is same in this case

    season_choices = (('Fall', 'Fall'), ('Winter', 'Winter'), ('Summer', 'Summer'))

    course_code = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_code')
    usefulness_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    difficulty_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    instructor_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    comment = models.TextField()
    instructor = models.CharField(max_length=200)
    taken_season = models.CharField(max_length=200, choices=(season_choices), blank=False, default="Fall")
    taken_year = models.IntegerField(choices=(year_choices), blank=False, default="2019")
    created_at = models.DateTimeField(auto_now=True)
    anonymous = models.BooleanField()
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

courses/forms.py
from django import forms
from django.forms import ModelChoiceField
from .models import Review, Course, Syllabus

class ReviewForm(forms.ModelForm):

    choices=(
        ('EXAMPLE', 'example'),
    )

    instructor = forms.CharField(widget=forms.Select(choices=choices))

    def __init__(self, *args, **kwargs):
        instructors = kwargs.pop('instructors')
        super(ReviewForm, self).__init__(*args, **kwargs)
        instructors = instructors
        instructors = tuple(zip(instructors, instructors))
        self.fields['instructor'].choices = instructors

    class Meta:
        model = Review
        fields = ('usefulness_rating', 'difficulty_rating', 'instructor_rating', 'comment', 'instructor', 'taken_season', 'taken_year', 'anonymous')

class SyllabusForm(forms.ModelForm):

    class Meta:
        model = Syllabus
        fields = ('syllabus',)

courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from .models import Category, Course, Review, Syllabus
from .forms import ReviewForm, SyllabusForm
from django.db.models import Avg
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
import json

def home(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'courses/home.html', context)

def category(request, category):
    category_object = Category.objects.get(category=category)
    course_list = Course.objects.all().filter(category=category).order_by('number')
    context = {
        'categories': category_object,
        'courses': course_list
    }
    return render(request, 'courses/category.html', context)

def course(request, category, number):
    course_object = Course.objects.get(category=category, number=number)
    reviews = Review.objects.all().filter(course_code_id=course_object.pk).order_by('-created_at')

    form = SyllabusForm()

    try:
        syllabus = Syllabus.objects.get(course_id=course_object.pk)
    except Syllabus.DoesNotExist:
        syllabus = None

    if reviews:
        usefulness_average = round(list(reviews.aggregate(Avg('usefulness_rating')).values())[0], 1)
        difficulty_average = round(list(reviews.aggregate(Avg('difficulty_rating')).values())[0], 1)
        instructor_average = round(list(reviews.aggregate(Avg('instructor_rating')).values())[0], 1)
        overall_average = round((usefulness_average + difficulty_average + instructor_average) / 3, 1)
    else:
        overall_average = 0
        usefulness_average = 0
        difficulty_average = 0
        instructor_average = 0

    reviews_json = json.dumps(list(reviews.values('usefulness_rating', 'difficulty_rating', 'instructor_rating', 'comment', 'instructor', 'taken_season', 'taken_year', 'created_at', 'anonymous', 'author')), cls=DjangoJSONEncoder)


    context = {
        'course': course_object,
        'usefulness_average': usefulness_average,
        'difficulty_average': difficulty_average,
        'instructor_average': instructor_average,
        'overall_average': overall_average,
        'reviews_json': reviews_json,
        'reviews': reviews,
        'syllabus': syllabus,
        'form': form,
    }

    return render(request, 'courses/course.html', context)

# def syllabus(request, id):
#     course_id = Course.objects.get(pk=id)
#     message = {'none': 'nothing has been done'}
#
#     if request.method == "POST" and request.is_ajax():
#         print("request is ajax")
#         form = SyllabusForm(request.POST, files=request.FILES)
#         print(form.errors)
#         if form.is_valid():
#             print("form is valid")
#             syllabus = form.save(commit=False)
#             syllabus.uploader = request.user
#             syllabus.course = course_id
#             syllabus.save()
#             message = {'success': 'Syllabus has been successfully uploaded'}
#     else:
#         print("form is not valid")
#         form = SyllabusForm()
#         message = {'error': 'There was an error trying to upload the syllabus, please try again'}
#
#     return JsonResponse(message)

def syllabus(request, id):
    course = Course.objects.get(pk=id)

    if request.method == "POST":
        form = SyllabusForm(request.POST, files=request.FILES)
        print(form.errors)
        if form.is_valid():
            syllabus = form.save(commit=False)
            syllabus.uploader = request.user
            syllabus.course = course
            syllabus.save()
            messages.success(request, 'Thank you for submitting a syllabus, it was received successfully.')
            return redirect('course', category=course.category, number=course.number)
    else:
        form = SyllabusForm()


@login_required
def review(request, category, number):
    course_object=Course.objects.get(category=category, number=number)

    if request.method == "POST":
        data = request.POST

        if data['instructor'] == 'Other':
            instructor_val = data['other_instructor']
        else:
            instructor_val = data['instructor']

        form = ReviewForm(request.POST, instructors=course_object.instructors)
        if form.is_valid():
            review = form.save(commit=False)

            if data['instructor'] == 'Other':
                instructor_val = data['other_instructor']
                course_object.instructors.append(instructor_val)
                course_object.instructors = sorted(course_object.instructors)
                course_object.save()
            else:
                instructor_val = data['instructor']

            review.instructor = instructor_val
            review.course_code = course_object
            review.author = request.user
            review.save()
            messages.success(request, 'Your review has been successfully submitted.')
            return redirect('course', category=category, number=number)
    else:
        form = ReviewForm(instructors=course_object.instructors)

    context = {
        'form': form,
        'course': course_object
    }

    return render(request, 'courses/review.html', context)

courses/templates/courses/category.html
{% extends 'base.html' %}

{% block title %}- {{ categories.category_title }}{% endblock title %}

{% block content %}

<div class="ui container">
  <h2>{{ categories.category }} - {{ categories.category_title }}</h2>
  <table class="ui selectable celled table">
    <thead>
      <tr>
        <th>Course Code</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      {% for course in courses %}
      <tr class="selectable" onclick="window.location.href='{% url 'course' category=course.category number=course.number %}'">
        <td>{{ course.code }}</td>
        <td>{{ course.title }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

courses/templates/courses/course.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}- {{ course.title }}{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/course.css' %}">

<div class="ui container">
  {% if messages %}
    {% for message in messages %}
      <div class="ui {% if message.tags == "success" %}positive{% else %}negative{% endif %} message">
        <i class="close icon"></i>
        <div class="header">
          {{ message }}
        </div>
      </div>
    {% endfor %}
  {% endif %}

  <div class="ui grid">
    <div class="six wide column">
      <h1>{{ course.code }}</h1>
    </div>

    {# conditional logic = if there is syllabus uploaded for the course, view syllabus button, if there isn't, show upload syllabus button #}
    <div class="right floated right aligned ten wide column">
      <button onclick="window.location.href = '{% url 'review' category=course.category number=course.number %}'" class="ui floated blue button header-btn">
        Write Review
      </button>
      {% if syllabus %}
      {# view syllabus #}
      <button class="ui right floated button header-btn" id="view-syllabus">View Syllabus</button>

      <div class="ui modal" id="view-modal">
        <i class="close icon"></i>
        <div class="header">
          {{ course.code }} Syllabus
        </div>
        <div id="syllabus"></div>
      </div>
      {% else %}
      {# upload syllabus #}
      <button class="ui button" id="upload-syllabus">Upload Syllabus</button>

      <div class="ui modal" id="upload-modal">
        <i class="close icon"></i>
        <div class="header">
          {{ course.code }} Syllabus Upload
        </div>

        {% if user.is_authenticated %}
        <div class="modal-margin">
          <div class="field six wide">
            <div class="ui action input" id="upload-modal-div">
              <form method="post" enctype="multipart/form-data" id="syllabus-form" url="{% url 'syllabus' id=course.id %}" action="{% url 'syllabus' id=course.id %}" class="ui form">
                {% csrf_token %}
                <div class="ui icon input syllabus-upload">
                  <input type="text" placeholder="Choose a file..." readonly class="syllabus-input">
                  <input type="file" name="syllabus" required id="id_syllabus" style="display: none!important;" />
                  <i class="inverted circular cloud upload alternate icon"></i>
                </div>
              </form>
            </div>
          </div>

          <p class="login-prompt">Only PDF files under 5 MB are accepted.</p>
          <a href="{% url 'syllabus_tutorial' %}" target="_blank" class="login-prompt">How do I download syllabuses from Canvas?</a>
        </div>

        <div class="actions">
          <div class="ui black deny button">
            Cancel
          </div>
          <button class="ui positive right labeled icon button" id="syllabus-submit-button" type="submit" form="syllabus-form-ajax" value="Submit">
            Submit
            <i class="checkmark icon"></i>
          </button>
        </div>

        {% else %}
        <div class="modal-margin">
          <h4 class="login-prompt">You must <a href="{% url 'login' %}?next={{request.get_full_path}}">login</a> before you can upload a syllabus.</h4>
        </div>
        <div class="actions">
          <div class="ui black deny button">
            Close
          </div>
        </div>
        {% endif %}
      </div> {# end of modal #}
      {% endif %}
    </div>
  </div>

  <h3>{{ course.title }}</h3>
  <p>{{ course.description|linebreaks }}</p>
  <p><small>Last Updated: {{ course.updated_at|date:"N jS, Y" }}</small></p>

  <div class="ui horizontal divider">
    <h3 class="header">
      Instructors
      </h4>
  </div>

  {% if course.instructors %}
  <div class="instructor-container">
    {% for instructor in course.instructors %}
    <button class="ui basic small button instructor-button" id="{{ instructor.split|join:"_" }}">
      {{ instructor }}
    </button>
    {% endfor %}
  </div>

  {% else %}
  <p>There are currently no listed instructors for this course.</p>
  {% endif %}

  <div class="ui horizontal divider">
    <h3 class="header">
      {% if reviews %}
      {% if reviews.count > 1 %}
      {{ reviews.count }} Reviews
      {% else %}
      {{ reviews.count }} Review
      {% endif %}
      <div class="ui huge star rating" data-rating="{{ overall_average|floatformat:"0" }}"></div>
      {% else %}
      Reviews
      {% endif %}
    </h3>
  </div>

  {% if reviews %}
  <div class="ui centered grid">
    <div class="four column stackable row">
      <div class="column">
        <h5 class="review-category-heading">Usefulness</h5>:
        <div class="ui star rating" data-rating="{{ usefulness_average|floatformat:"0" }}"></div>
        <span>({{ usefulness_average }})</span>
      </div>
      <div class="column">
        <h5 class="review-category-heading">Difficulty</h5>:
        <div class="ui star rating" data-rating="{{ difficulty_average|floatformat:"0" }}"></div>
        <span>({{ difficulty_average }})</span>
      </div>
      <div class="column">
        <h5 class="review-category-heading">Instructor</h5>:
        <div class="ui star rating" data-rating="{{ instructor_average|floatformat:"0" }}"></div>
        <span>({{ instructor_average }})</span>
      </div>
    </div>
  </div>
  {% else %}
  <p>There are currently no reviews for this course.</p>
  {% endif %}

  <div class="ui divider"></div>
  {% if reviews %}
  <div class="reviews">
    {% for review in reviews %}
    <div class="review" data-instructor="{{ review.instructor.split|join:"_" }}" style="width: 100%" id="review">
      <div class="ui grid">
        <div class="row">
          <div class="four wide computer five wide mobile column">
            {# if review is anonymous, show generic image, else show facebook profile pic #}
            {% if review.anonymous == True %}
            <div class="ui horizontal list">
              <div class="item">
                <div class="ui sub header">
                  <img class="ui small circular image" src="{% static 'img/bulldog.png' %}" alt="" style="object-fit: contain;">
                  Anonymous
                </div>
              </div>
            </div>
            {% else %}
            <div class="ui horizontal list">
              <div class="item">
                <div class="ui sub header">
                  <img class="ui small circular image" src="{{ review.author.social_auth.all.0.extra_data.picture.data.url }}" alt="">
                  {{ review.author.social_auth.all.0.extra_data.name }}
                </div>
              </div>
            </div>
            {% endif %}
          </div>

          <div class="twelve wide computer seven wide mobile column">
            <div class="ui grid">
              <div class="four column stackable row">
                <div class="column" id="review-column">
                  <div class="meta">
                    Usefulness:
                    <div class="ui star rating" data-rating="{{ review.usefulness_rating }}"></div>
                  </div>
                </div>
                <div class="column" id="review-column">
                  <div class="meta">
                    Difficulty:
                    <div class="ui star rating" data-rating="{{ review.difficulty_rating }}"></div>
                  </div>
                </div>
                <div class="column" id="review-column">
                  <div class="meta">
                    Instructor:
                    <div class="ui star rating" data-rating="{{ review.instructor_rating }}"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="four wide computer five wide mobile column">
            <div class="item" id="meta-item">
              <div class="meta" id="review-meta">
                Session: {{ review.taken_season }} {{ review.taken_year }}
              </div>
              <div class="meta" id="review-meta">
                Instructor: {{ review.instructor }}
              </div>
              <div class="meta" id="review-meta">
                {{ review.created_at|date:"N jS, Y"  }}
              </div>
            </div>
          </div>

          <div class="twelve wide computer seven wide mobile column">
            <div class="content">
              <div class="meta">
                {{ review.comment|linebreaks }}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="ui divider"></div>
      </div>
      {% endfor %}
      <div class="message-div">
        <p>There are currently no reviews for this instructor.</p>
      </div>
  </div>
  {% else %}
  <p>There are no reviews.</p>
  {% endif %}

  <button onclick="window.location.href = '{% url 'review' category=course.category number=course.number %}'" class="ui floated blue labeled icon button header-btn" id="review-button-test">
    <i class="star icon"></i>
    Write Review
  </button>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfobject/2.1.1/pdfobject.min.js"></script>
<script>
  PDFObject.embed("{{ syllabus.syllabus.url }}", "#syllabus");
</script>
<script type="text/javascript" src="{% static 'js/course.js' %}"></script>
{% endblock content %}

courses/templates/courses/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/home.css' %}">

<div class="ui container">
  {% if messages %}
    {% for message in messages %}
      <div class="ui {% if message.tags == "success" %}positive{% else %}negative{% endif %} message">
        <i class="close icon"></i>
        <div class="header">
          {{ message }}
        </div>
      </div>
    {% endfor %}
  {% endif %}

  <div class="ui four stackable cards">
    {% for category in categories %}
      <div class="card" id="category-card" onclick="window.location.href='{% url 'category' category=category.category %}'">
        <div class="image">
          <img src="{% static 'img/categories/'|add:category.category|add:'.jpg' %}" alt="" onerror="this.onerror=null;this.src='{% static 'img/categories/General'|add:'.jpg' %}'" class="category-img">
        </div>
        <div class="content">
          <a href="{% url 'category' category=category.category %}" class="header">{{ category.category }}</a>
            <div class="meta">{{ category.category_title|truncatechars:30 }}</div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

<script>
$('.message .close')
  .on('click', function() {
    $(this)
      .closest('.message')
      .transition('fade')
    ;
  })
;
</script>
{% endblock content %}

courses/templates/courses/review.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<div class="ui container">
  <h1>{{ course.code }}</h1>
  <h3>{{ course.title }}</h3>

  <form method="POST" class="ui form" id="post-form" novalidate>

    <h4 class="ui dividing header">General Information</h4>

    <div class="field">
      <label>Session</label>
      <div class="two fields">

        <!-- season  -->
        <div class="field">
          <div class="ui selection dropdown" id="id_taken_season">
            <input type="hidden" name="season-dd">
            <i class="dropdown icon"></i>
            <div class="default text">Term</div>
            <div class="menu">
              {% for value, text in form.taken_season.field.choices %}
              <div class="item" season-value="{{ value }}">{{ text }}</div>
              {% endfor %}
            </div>
          </div>
        </div>

        <!-- year -->
        <div class="field">
          <div class="ui selection dropdown" id="id_taken_year">
            <input type="hidden" name="year-dd">
            <i class="dropdown icon"></i>
            <div class="default text">Year</div>
            <div class="menu">
              {% for value, text in form.taken_year.field.choices %}
              <div class="item" year-value="{{ value }}">{{ text }}</div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>

      <!-- instructor -->
      <div class="field">
        <label for="id_instructor_rating">Instructor</label>
        <div class="ui selection dropdown" id="id_instructor">
          <input type="hidden" name="instructor-dd">
          <i class="dropdown icon"></i>
          <div class="default text">Instructor</div>
          <div class="menu">
            {% for value, text in form.instructor.field.choices %}
            <div class="item" instructor-value="{{ value }}">{{ text }}</div>
            {% endfor %}
            <div class="item"><b>Other</b></div>
          </div>
        </div>
      </div>

      <!-- conditional instructor input field -->
      <div class="field" style="display:none;"id="other_instructor_div">
        <label>Instructor Name</label>
        <input type="text" placeholder="Who was your instructor?" id="other_instructor_text">
      </div>

      <h4 class="ui dividing header">Review</h4>

      <div class="three fields">
        <div class="field">
          <label>Usefulness</label>
          <div class="ui huge star rating" name="usefulness_rating" required id="id_usefulness_rating"></div>
        </div>

        <div class="field">
          <label>Difficulty</label>
          <div class="ui huge star rating" name="difficulty_rating" required id="id_difficulty_rating"></div>
        </div>

        <div class="field">
          <label>Instructor</label>
          <div class="ui huge star rating" name="instructor_rating" required id="id_instructor_rating"></div>
        </div>
      </div>

    <div class="field">
      <label>Comment</label>
      <textarea name="comment" required id="id_comment" cols="30" rows="10" style="font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;" placeholder="What did you like or dislike about this course and the professor?"></textarea>
    </div>

    <div class="field">
      <div class="ui toggle checkbox" id="id_anonymous">
        <input type="checkbox" tabindex="0" class="hidden">
        <label>Post Anonymously</label>
      </div>
    </div>

    <div class="ui error message"></div>

    <button class="ui button" type="submit">Post Review</button>
  </form>
</div>

<script type="text/javascript">
  url_review = "{% url 'review' category=course.category number=course.number %}"
  url_course = "{% url 'course' category=course.category number=course.number %}"
  csrf_token = "{{csrf_token}}"
</script>

<script type="text/javascript" src="{% static 'js/review.js' %}"></script>




{% endblock content %}